project:
  type: book

book:
  title: "EDA for Python"
  date: last-modified
  repo-url: https://github.com/yeonkyupark/python4eda 
  repo-branch: main
  repo-actions: [edit]
  favicon: logo.png
  page-footer: 
    left: "Copyright(c) 2026 YK" 
    right: "Python for Data Analytics"
  sidebar: 
    tools:
      - icon: instagram
        href: https://www.instagram.com/yeonkyu.park/
      - icon: globe
        href: https://yeonkyupark.github.io/
    collapse-level: 1
  chapters:
    - index.qmd
    - ch00.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd
    - ch05.qmd
    - ch06.qmd
    - ch07.qmd

number-sections: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    mermaid:
      theme: neutral
      
toc: true
toc-depth: 4
toc-title: 목차

language:
  crossref-apx-prefix: 참고자료
  section-title-appendices: 참고자료

crossref:
  appendix-title: "참고자료"
  appendix-delim: ":"

execute:
  freeze: auto
  warning: false
  message: false

jupyter: python3
